"""Init stock table

Revision ID: 43d4ee072195
Revises:
Create Date: 2024-06-18 12:35:27.000891

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "43d4ee072195"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("purchased_amount", sa.Integer(), nullable=True),
        sa.Column("purchased_status", sa.String(), nullable=True),
        sa.Column("request_date", sa.Date(), nullable=True),
        sa.Column("company_code", sa.String(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("stock_values", sa.JSON(), nullable=True),
        sa.Column("performance_data", sa.JSON(), nullable=True),
        sa.Column("competitors", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("stocks_pkey")),
    )
    op.create_index(op.f("stocks_id_idx"), "stocks", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("stocks_id_idx"), table_name="stocks")
    op.drop_table("stocks")
    # ### end Alembic commands ###
